import type { Game2048Spec } from "@/schemas/game-spec";

export type Board2048 = number[][];
export type Direction2048 = "up" | "down" | "left" | "right";
export type Game2048State = { status: "ready" | "running" | "paused" | "won" | "lost"; board: Board2048; score: number; seed: number; flashFor: number };

function random(seed: number) { const next = (seed * 1664525 + 1013904223) >>> 0; return { seed: next, value: next / 4_294_967_296 }; }
export function emptyBoard(size = 4): Board2048 { return Array.from({ length: size }, () => Array<number>(size).fill(0)); }
export function mergeLine(line: number[]) { const values = line.filter(Boolean), merged: number[] = []; let score = 0; for (let index = 0; index < values.length; index += 1) { if (values[index] === values[index + 1]) { const value = values[index] * 2; merged.push(value); score += value; index += 1; } else merged.push(values[index]); } return { line: [...merged, ...Array(line.length - merged.length).fill(0)], score }; }
function rotate(board: Board2048) { return board[0].map((_, column) => board.map((row) => row[column]).reverse()); }
function turn(board: Board2048, times: number) { let result = board.map((row) => [...row]); for (let index = 0; index < times; index += 1) result = rotate(result); return result; }
export function move2048Board(board: Board2048, direction: Direction2048) { const turns = direction === "left" ? 0 : direction === "up" ? 3 : direction === "right" ? 2 : 1, oriented = turn(board, turns); let score = 0; const moved = oriented.map((line) => { const result = mergeLine(line); score += result.score; return result.line; }); const next = turn(moved, (4 - turns) % 4), changed = next.some((row, y) => row.some((value, x) => value !== board[y][x])); return { board: next, score, changed }; }
export function spawn2048(board: Board2048, seed: number) { const open: Array<[number, number]> = []; board.forEach((row, y) => row.forEach((value, x) => { if (!value) open.push([x, y]); })); if (!open.length) return { board: board.map((row) => [...row]), seed }; const first = random(seed), second = random(first.seed), [x, y] = open[Math.floor(first.value * open.length)]; const next = board.map((row) => [...row]); next[y][x] = second.value < .9 ? 2 : 4; return { board: next, seed: second.seed }; }
export function canMove2048(board: Board2048) { return board.some((row, y) => row.some((value, x) => !value || value === row[x + 1] || value === board[y + 1]?.[x])); }
export function create2048State(config: Game2048Spec): Game2048State { const first = spawn2048(emptyBoard(config.game2048.boardSize), config.game2048.seed), second = spawn2048(first.board, first.seed); return { status: "ready", board: second.board, score: 0, seed: second.seed, flashFor: 0 }; }
export function update2048(state: Game2048State, config: Game2048Spec, direction?: Direction2048): Game2048State { if (state.status !== "running" || !direction) return state; const moved = move2048Board(state.board, direction); if (!moved.changed) return { ...state, status: canMove2048(state.board) ? "running" : "lost" }; const spawned = spawn2048(moved.board, state.seed), score = state.score + moved.score, won = spawned.board.some((row) => row.some((value) => value >= config.game2048.targetTile)); return { ...state, board: spawned.board, seed: spawned.seed, score, flashFor: .2, status: won ? "won" : canMove2048(spawned.board) ? "running" : "lost" }; }
