import { describe, expect, it } from "vitest";
import { collectDemoGame, demoGame } from "@/data/demo-game";
import { generateGameSpec, INITIAL_MAX_TOKENS, MAX_MODEL_CALLS, RETRY_MAX_TOKENS, type DeepSeekChatRequest } from "./generate-game";
import { toSafeGenerateError } from "./errors";
const input={prompt:"生成一个海底主题的接金币游戏，玩家有三条生命，在30秒内接到15颗珍珠，同时躲避水母。",styleId:"deep-space" as const};
const response=(content:string|null,finish_reason:string|null="stop")=>({choices:[{finish_reason,message:{content}}]});
const underwater={...collectDemoGame,title:"海底珍珠挑战",visualTheme:"ocean" as const,world:{...collectDemoGame.world,duration:30},player:{...collectDemoGame.player,lives:3},collect:{...collectDemoGame.collect,targetCount:15,collectibleKind:"pearl" as const,hazardKind:"jellyfish" as const}};
describe("DeepSeek game generation",()=>{
 it("uses one call for valid current collect JSON",async()=>{let calls=0;const game=await generateGameSpec(input,{apiKey:"placeholder",create:async()=>{calls+=1;return response(JSON.stringify(underwater))}});expect(calls).toBe(1);expect(game).toMatchObject({genre:"collect",visualTheme:"ocean",world:{duration:30},player:{lives:3}});if(game.genre==="collect")expect(game.collect).toMatchObject({targetCount:15,collectibleKind:"pearl",hazardKind:"jellyfish"});});
 it("repairs legacy collect fields in exactly one extra call",async()=>{const old=structuredClone(underwater) as unknown as Record<string,unknown>,legacy=old.collect as Record<string,unknown>;delete legacy.targetCount;legacy["target"+"Score"]=300;legacy["score"+"PerCoin"]=50;const requests:DeepSeekChatRequest[]=[];const game=await generateGameSpec(input,{apiKey:"placeholder",create:async request=>{requests.push(request as DeepSeekChatRequest);return response(JSON.stringify(requests.length===1?old:underwater))}});expect(requests).toHaveLength(2);expect(requests[1].max_tokens).toBe(RETRY_MAX_TOKENS);expect(requests[1].messages[1].content).toContain("collect.targetCount");expect(game.genre).toBe("collect");});
 it("repairs a missing visual field and keeps underwater constraints",async()=>{const incomplete={...underwater,collect:{...underwater.collect}};delete (incomplete.collect as Partial<typeof incomplete.collect>).collectibleKind;let calls=0;const game=await generateGameSpec(input,{apiKey:"placeholder",create:async()=>response(JSON.stringify(calls++?underwater:incomplete))});expect(game.genre).toBe("collect");if(game.genre==="collect")expect(game.collect.collectibleKind).toBe("pearl");});
 it("rejects two invalid schema results after at most two calls",async()=>{let calls=0;const invalid={...underwater,collect:{...underwater.collect,unknown:"no"}};await expect(generateGameSpec(input,{apiKey:"placeholder",create:async()=>{calls+=1;return response(JSON.stringify(invalid))}})).rejects.toMatchObject({code:"invalid_output"});expect(calls).toBe(MAX_MODEL_CALLS);});
 it("rejects invalid JSON and retries one truncated response",async()=>{await expect(generateGameSpec(input,{apiKey:"placeholder",create:async()=>response("{")})).rejects.toMatchObject({code:"invalid_json"});const requests:DeepSeekChatRequest[]=[];await generateGameSpec(input,{apiKey:"placeholder",create:async request=>{requests.push(request as DeepSeekChatRequest);return response(JSON.stringify(underwater),requests.length===1?"length":"stop")}});expect(requests.map(item=>item.max_tokens)).toEqual([INITIAL_MAX_TOKENS,RETRY_MAX_TOKENS]);});
 it("retries one empty completion within the same two-call cap",async()=>{let calls=0;const game=await generateGameSpec(input,{apiKey:"placeholder",create:async()=>response(calls++?JSON.stringify(underwater):null)});expect(calls).toBe(2);expect(game.genre).toBe("collect");});
 it("keeps safe error mapping and no real SDK calls",()=>{expect(toSafeGenerateError({status:401}).code).toBe("authentication_failed");expect(toSafeGenerateError({status:429}).code).toBe("rate_limited");expect(demoGame.genre).toBe("dodge");});
});
