"use client";
import { useState } from "react";
import { GameCanvas } from "@/components/studio/game-canvas";
import { GenreCanvas } from "@/components/studio/genre-canvas";
import type { GameState } from "@/game-engine/types";
import type { GameSpec } from "@/types/game";
import type { SavedGameSource } from "@/types/saved-game";
export function getPreviewBadge(source: SavedGameSource) { return source === "ai" ? "AI 已生成" : "Demo Preview"; }
export function GamePreview({ game, resetToken, source }: { game: GameSpec; resetToken: number; source: SavedGameSource }) { const [, setSnapshot] = useState<GameState | null>(null); const [restart, setRestart] = useState(0); const fullscreen = async () => { const element = document.querySelector<HTMLElement>(".canvas-shell"); try { if (!element) return; if (document.fullscreenElement) await document.exitFullscreen(); else await element.requestFullscreen(); } catch {} }; return <section className="game-preview" aria-labelledby="game-title"><div className="preview-heading"><div><p className="eyebrow">实时预览</p><div className="title-with-tag"><h1 id="game-title">{game.title}</h1><span className="status-tag"><i />{getPreviewBadge(source)}</span></div><p>{game.description}</p></div><div className="preview-actions"><button aria-label="重新开始" onClick={() => setRestart((value) => value + 1)}>↻</button><button aria-label="全屏预览" onClick={fullscreen}>⛶</button></div></div>{game.genre === "dodge" ? <GameCanvas key={resetToken + restart} config={game} onStateChange={setSnapshot} /> : <GenreCanvas key={resetToken + restart} config={game} />}<p className="control-guide">操作方式：{game.controls.description}。点击游戏画面可激活键盘控制，空格可暂停或继续。</p><div className="rules-summary"><div><span className="rules-icon">✦</span><div><p className="eyebrow">游戏规则</p><h2>如何完成当前挑战</h2></div></div><ol>{game.rules.summary.map((rule) => <li key={rule}>{rule}</li>)}</ol></div></section>; }
