"use client";

import { type PointerEvent, useCallback, useEffect, useRef, useState } from "react";
import { EMPTY_INPUT, KEY_TO_DIRECTION, MAX_DELTA_SECONDS } from "@/game-engine/constants";
import { createGameState } from "@/game-engine/create-state";
import { renderGame } from "@/game-engine/render";
import { getVisualThemeTokens } from "@/game-engine/visual-theme";
import { getGameOverlayCopy } from "@/game-engine/result-copy";
import { updateGame } from "@/game-engine/update";
import type { GameConfig, GameState, GameStatus, InputState } from "@/game-engine/types";

type Props = { config: GameConfig; onStateChange: (state: GameState) => void };

export function GameCanvas({ config, onStateChange }: Props) {
  const visual = getVisualThemeTokens(config.visualTheme);
  const canvasRef = useRef<HTMLCanvasElement>(null); const containerRef = useRef<HTMLDivElement>(null); const stateRef = useRef<GameState>(createGameState(config)); const inputRef = useRef<InputState>({ ...EMPTY_INPUT }); const frameRef = useRef<number | null>(null); const previousRef = useRef<number | null>(null); const [status, setStatus] = useState<GameStatus>("ready"); const [hud, setHud] = useState({ lives: config.player.lives, score: 0, timeLeft: config.world.duration });
  const publish = useCallback((next: GameState) => { stateRef.current = next; setStatus(next.status); setHud({ lives: next.player.lives, score: next.score, timeLeft: next.timeLeft }); onStateChange(next); }, [onStateChange]);
  const reset = useCallback((start = false) => { inputRef.current = { ...EMPTY_INPUT }; const next = createGameState(config); next.status = start ? "running" : "ready"; previousRef.current = null; publish(next); }, [config, publish]);
  const begin = useCallback(() => { if (stateRef.current.status === "paused") { publish({ ...stateRef.current, status: "running" }); } else { reset(true); } containerRef.current?.focus(); }, [publish, reset]);
  const pause = useCallback(() => { if (stateRef.current.status === "running") publish({ ...stateRef.current, status: "paused" }); }, [publish]);
  useEffect(() => { const canvas = canvasRef.current; const container = containerRef.current; if (!canvas || !container) return; const ctx = canvas.getContext("2d"); if (!ctx) return;
    const resize = () => { const rect = container.getBoundingClientRect(); const dpr = Math.min(window.devicePixelRatio || 1, 2); canvas.width = Math.max(1, Math.round(rect.width * dpr)); canvas.height = Math.max(1, Math.round(rect.height * dpr)); canvas.style.width = `${rect.width}px`; canvas.style.height = `${rect.height}px`; ctx.setTransform(canvas.width / config.world.width, 0, 0, canvas.height / config.world.height, 0, 0); renderGame(ctx, stateRef.current, config); };
    const observer = new ResizeObserver(resize); observer.observe(container); resize();
    const tick = (timestamp: number) => { const previous = previousRef.current ?? timestamp; const delta = Math.min((timestamp - previous) / 1000, MAX_DELTA_SECONDS); previousRef.current = timestamp; const current = stateRef.current; if (current.status === "running") { const next = updateGame(current, config, inputRef.current, delta); if (next !== current) publish(next); } renderGame(ctx, stateRef.current, config); frameRef.current = requestAnimationFrame(tick); }; frameRef.current = requestAnimationFrame(tick);
    return () => { observer.disconnect(); if (frameRef.current) cancelAnimationFrame(frameRef.current); };
  }, [config, publish]);
  useEffect(() => { const isControlKey = (code: string) => code in KEY_TO_DIRECTION; const changeKey = (event: KeyboardEvent, value: boolean) => { const direction = KEY_TO_DIRECTION[event.code]; if (!direction) return; const active = document.activeElement === containerRef.current || stateRef.current.status === "running"; if (!active) return; event.preventDefault(); inputRef.current[direction] = value; };
    const onDown = (event: KeyboardEvent) => { if (event.code === "Space" && (document.activeElement === containerRef.current || stateRef.current.status === "running")) { event.preventDefault(); if (stateRef.current.status === "running") pause(); else begin(); return; } if (isControlKey(event.code)) changeKey(event, true); }; const onUp = (event: KeyboardEvent) => changeKey(event, false); const onVisibility = () => { if (document.hidden) pause(); };
    window.addEventListener("keydown", onDown); window.addEventListener("keyup", onUp); document.addEventListener("visibilitychange", onVisibility); window.addEventListener("blur", pause); return () => { window.removeEventListener("keydown", onDown); window.removeEventListener("keyup", onUp); document.removeEventListener("visibilitychange", onVisibility); window.removeEventListener("blur", pause); };
  }, [begin, pause]);
  const press = (direction: keyof InputState) => (event: PointerEvent<HTMLButtonElement>) => { event.preventDefault(); inputRef.current[direction] = true; containerRef.current?.focus(); };
  const release = (direction: keyof InputState) => () => { inputRef.current[direction] = false; };
  const overlay = status === "running" ? null : getGameOverlayCopy(status, config.title, config.world.duration, hud.score);
  return <><div ref={containerRef} className="canvas-shell" tabIndex={0} aria-label={`${config.title}游戏区域，使用方向键、WASD 或触屏按钮控制飞船`} onClick={() => containerRef.current?.focus()}><canvas ref={canvasRef} /><div className="canvas-hud" aria-live="polite"><div><span>生命</span>{Array.from({ length: hud.lives }).map((_, index) => <b key={index} style={{ color: visual.hud }}>♥</b>)}</div><div><span>得分</span><b style={{ color: visual.hud }}>{String(Math.floor(hud.score)).padStart(5, "0")}</b></div><div><span>剩余时间</span><b style={{ color: visual.hud }}>00:{String(Math.ceil(hud.timeLeft)).padStart(2, "0")}</b></div></div>{status === "running" && <button className="canvas-pause" type="button" onClick={pause} aria-label="暂停游戏">Ⅱ 暂停</button>}{overlay && <div className="game-overlay"><div className={`overlay-emblem ${status}`} aria-hidden="true">{status === "won" ? "✦" : status === "lost" ? "×" : status === "paused" ? "Ⅱ" : "▲"}</div><h2>{overlay.title}</h2><p>{overlay.text}</p><button className="button button-primary" type="button" onClick={begin}>{overlay.action} <span aria-hidden="true">→</span></button></div>}</div><div className="touch-controls" aria-label="触屏方向控制"><button aria-label="向上移动" type="button" onPointerDown={press("up")} onPointerUp={release("up")} onPointerCancel={release("up")} onPointerLeave={release("up")}>↑</button><div><button aria-label="向左移动" type="button" onPointerDown={press("left")} onPointerUp={release("left")} onPointerCancel={release("left")} onPointerLeave={release("left")}>←</button><button aria-label="向下移动" type="button" onPointerDown={press("down")} onPointerUp={release("down")} onPointerCancel={release("down")} onPointerLeave={release("down")}>↓</button><button aria-label="向右移动" type="button" onPointerDown={press("right")} onPointerUp={release("right")} onPointerCancel={release("right")} onPointerLeave={release("right")}>→</button></div></div></>;
}
