"use client";

import { type PointerEvent, useEffect, useRef, useState } from "react";
import { EMPTY_INPUT, KEY_TO_DIRECTION, MAX_DELTA_SECONDS } from "@/game-engine/constants";
import { createCollectState, updateCollect, type CollectState } from "@/game-engine/collect";
import { createMazeState, updateMaze, type MazeState } from "@/game-engine/maze";
import { createSnakeState, updateSnake, type SnakeState } from "@/game-engine/snake";
import { getVisualThemeTokens, renderVisualTheme } from "@/game-engine/visual-theme";
import type { InputState } from "@/game-engine/types";
import type { CollectGameSpec, MazeGameSpec, SnakeGameSpec } from "@/schemas/game-spec";

type Config = CollectGameSpec | MazeGameSpec | SnakeGameSpec;
type State = CollectState | MazeState | SnakeState;
const makeState = (config: Config): State => config.genre === "collect" ? createCollectState(config) : config.genre === "maze" ? createMazeState(config) : createSnakeState(config);

function renderItem(ctx: CanvasRenderingContext2D, kind: CollectGameSpec["collect"]["collectibleKind"], x: number, y: number, radius: number, color: string) { ctx.save(); ctx.translate(x, y); ctx.fillStyle = kind === "pearl" ? "#f6fcff" : color; ctx.beginPath(); if (kind === "star") { for (let index = 0; index < 10; index += 1) { const angle = -Math.PI / 2 + index * Math.PI / 5, length = index % 2 ? radius * .45 : radius; if (index) ctx.lineTo(Math.cos(angle) * length, Math.sin(angle) * length); else ctx.moveTo(Math.cos(angle) * length, Math.sin(angle) * length); } ctx.closePath(); } else if (kind === "gem") { ctx.moveTo(0, -radius); ctx.lineTo(radius * .7, 0); ctx.lineTo(0, radius); ctx.lineTo(-radius * .7, 0); ctx.closePath(); } else ctx.arc(0, 0, radius, 0, Math.PI * 2); ctx.fill(); ctx.restore(); }
function renderHazard(ctx: CanvasRenderingContext2D, kind: CollectGameSpec["collect"]["hazardKind"], x: number, y: number, radius: number, color: string) { ctx.save(); ctx.translate(x, y); ctx.fillStyle = color; if (kind === "jellyfish") { ctx.beginPath(); ctx.arc(0, -radius * .15, radius * .72, Math.PI, 0); ctx.lineTo(radius * .72, radius * .25); ctx.lineTo(-radius * .72, radius * .25); ctx.fill(); ctx.strokeStyle = color; for (const offset of [-.45, -.15, .15, .45]) { ctx.beginPath(); ctx.moveTo(offset * radius, radius * .2); ctx.quadraticCurveTo(offset * radius + radius * .15, radius * .6, offset * radius, radius); ctx.stroke(); } } else { ctx.beginPath(); ctx.arc(0, 0, radius, 0, Math.PI * 2); ctx.fill(); } ctx.restore(); }

export function GenreCanvas({ config }: { config: Config }) {
  const canvas = useRef<HTMLCanvasElement>(null), box = useRef<HTMLDivElement>(null), state = useRef<State>(makeState(config)), input = useRef<InputState>({ ...EMPTY_INPUT }), frame = useRef<number | null>(null), previous = useRef<number | null>(null);
  const [snapshot, setSnapshot] = useState<State>(() => makeState(config));
  const visual = getVisualThemeTokens(config.visualTheme);
  const publish = (next: State) => { state.current = next; setSnapshot(next); };
  const reset = (run = false) => { input.current = { ...EMPTY_INPUT }; const next = makeState(config); next.status = run ? "running" : "ready"; publish(next); };

  useEffect(() => {
    const element = canvas.current, wrapper = box.current, ctx = element?.getContext("2d"); if (!element || !wrapper || !ctx) return;
    const draw = () => { const current = state.current, width = config.world.width, height = config.world.height, tokens = getVisualThemeTokens(config.visualTheme); renderVisualTheme(ctx, config.visualTheme, width, height, 0);
      if (config.genre === "collect") { const collect = current as CollectState; collect.coins.forEach((coin) => renderItem(ctx, config.collect.collectibleKind, coin.x, coin.y, coin.radius, tokens.collectible)); collect.dangers.forEach((danger) => renderHazard(ctx, config.collect.hazardKind, danger.x, danger.y, danger.radius, tokens.hazard)); ctx.fillStyle = tokens.player; ctx.fillRect(collect.x - config.player.size, height - config.player.size * 2, config.player.size * 2, config.player.size); }
      else if (config.genre === "maze") { const maze = current as MazeState, cell = Math.min(width / config.maze.gridWidth, height / config.maze.gridHeight), offsetX = (width - cell * config.maze.gridWidth) / 2, offsetY = (height - cell * config.maze.gridHeight) / 2; for (let y = 0; y < maze.map.length; y += 1) for (let x = 0; x < maze.map[0].length; x += 1) { ctx.fillStyle = maze.map[y][x] ? tokens.wall : tokens.floor; ctx.fillRect(offsetX + x * cell, offsetY + y * cell, cell - 1, cell - 1); ctx.strokeStyle = tokens.grid; ctx.strokeRect(offsetX + x * cell, offsetY + y * cell, cell - 1, cell - 1); } ctx.fillStyle = tokens.glow; ctx.fillRect(offsetX + (config.maze.gridWidth - 2) * cell, offsetY + (config.maze.gridHeight - 2) * cell, cell - 2, cell - 2); ctx.fillStyle = tokens.player; ctx.beginPath(); ctx.arc(offsetX + (maze.x + .5) * cell, offsetY + (maze.y + .5) * cell, cell * .3, 0, Math.PI * 2); ctx.fill(); }
      else { const snake = current as SnakeState, cell = Math.min(width / config.snake.columns, height / config.snake.rows), offsetX = (width - cell * config.snake.columns) / 2, offsetY = (height - cell * config.snake.rows) / 2; ctx.fillStyle = tokens.floor; ctx.fillRect(offsetX, offsetY, cell * config.snake.columns, cell * config.snake.rows); ctx.strokeStyle = tokens.grid; for (let x = 0; x <= config.snake.columns; x += 1) { ctx.beginPath(); ctx.moveTo(offsetX + x * cell, offsetY); ctx.lineTo(offsetX + x * cell, offsetY + config.snake.rows * cell); ctx.stroke(); } for (let y = 0; y <= config.snake.rows; y += 1) { ctx.beginPath(); ctx.moveTo(offsetX, offsetY + y * cell); ctx.lineTo(offsetX + config.snake.columns * cell, offsetY + y * cell); ctx.stroke(); } ctx.fillStyle = tokens.collectible; ctx.shadowBlur = 16; ctx.shadowColor = tokens.glow; ctx.beginPath(); ctx.arc(offsetX + (snake.food.x + .5) * cell, offsetY + (snake.food.y + .5) * cell, cell * .28, 0, Math.PI * 2); ctx.fill(); ctx.shadowBlur = 0; snake.body.forEach((part, index) => { ctx.fillStyle = index === 0 ? tokens.player : tokens.particle; ctx.fillRect(offsetX + part.x * cell + 2, offsetY + part.y * cell + 2, cell - 4, cell - 4); }); }
    };
    const resize = () => { const rect = wrapper.getBoundingClientRect(), dpr = Math.min(window.devicePixelRatio || 1, 2); element.width = Math.max(1, Math.round(rect.width * dpr)); element.height = Math.max(1, Math.round(rect.height * dpr)); ctx.setTransform(element.width / config.world.width, 0, 0, element.height / config.world.height, 0, 0); draw(); };
    const observer = new ResizeObserver(resize); observer.observe(wrapper); resize();
    const tick = (time: number) => { const delta = Math.min((time - (previous.current ?? time)) / 1000, MAX_DELTA_SECONDS); previous.current = time; if (state.current.status === "running") publish(config.genre === "collect" ? updateCollect(state.current as CollectState, config, input.current, delta) : config.genre === "maze" ? updateMaze(state.current as MazeState, config, input.current, delta) : updateSnake(state.current as SnakeState, config, input.current, delta)); draw(); frame.current = requestAnimationFrame(tick); };
    frame.current = requestAnimationFrame(tick); return () => { observer.disconnect(); if (frame.current) cancelAnimationFrame(frame.current); };
  }, [config]);
  // reset is intentionally captured with the current config so a template switch replaces all input state.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { const setKey = (event: KeyboardEvent, value: boolean) => { const direction = KEY_TO_DIRECTION[event.code]; if (!direction) return; event.preventDefault(); input.current[direction] = value; }; const down = (event: KeyboardEvent) => { if (event.code === "Space") { event.preventDefault(); if (state.current.status === "running") publish({ ...state.current, status: "paused" }); else reset(true); } else setKey(event, true); }; const up = (event: KeyboardEvent) => setKey(event, false); const hide = () => { if (document.hidden && state.current.status === "running") publish({ ...state.current, status: "paused" }); }; window.addEventListener("keydown", down); window.addEventListener("keyup", up); document.addEventListener("visibilitychange", hide); return () => { window.removeEventListener("keydown", down); window.removeEventListener("keyup", up); document.removeEventListener("visibilitychange", hide); }; }, [config]);
  const press = (direction: keyof InputState) => (event: PointerEvent<HTMLButtonElement>) => { event.preventDefault(); input.current[direction] = true; }; const release = (direction: keyof InputState) => () => { input.current[direction] = false; };
  const collect = config.genre === "collect" ? snapshot as CollectState : null, maze = config.genre === "maze" ? snapshot as MazeState : null, snake = config.genre === "snake" ? snapshot as SnakeState : null, timed = collect ?? maze;
  return <><div ref={box} className="canvas-shell" tabIndex={0} aria-label={`${config.title}游戏区域`}><canvas ref={canvas} /><div className="canvas-hud"><div><span>{collect ? "生命" : maze ? "步数" : "长度"}</span><b style={{ color: visual.hud }}>{collect ? collect.lives : maze ? maze.steps : snake?.body.length}</b></div><div><span>{collect ? "已收集" : maze ? "出口" : "得分"}</span><b style={{ color: visual.hud }}>{collect ? `${collect.collectedCount} / ${config.genre === "collect" ? config.collect.targetCount : 0}` : maze ? "→" : `${snake?.score} / ${config.genre === "snake" ? config.snake.targetScore : 0}`}</b></div><div><span>{timed ? "剩余时间" : "状态"}</span><b style={{ color: visual.hud }}>{timed ? `00:${String(Math.ceil(timed.timeLeft)).padStart(2, "0")}` : snapshot.status === "running" ? "进行中" : "准备"}</b></div></div>{snapshot.status === "running" && <button className="canvas-pause" type="button" onClick={() => publish({ ...snapshot, status: "paused" })}>Ⅱ 暂停</button>}{snapshot.status !== "running" && <div className="game-overlay"><h2>{snapshot.status === "won" ? `${config.title}成功` : snapshot.status === "lost" ? `${config.title}失败` : snapshot.status === "paused" ? "游戏已暂停" : "开始游戏"}</h2><p>{snapshot.status === "lost" ? "调整方向后重新尝试。" : snapshot.status === "won" ? "挑战完成！" : "方向键 / WASD / 触屏按钮均可操作。"}</p><button className="button button-primary" type="button" onClick={() => snapshot.status === "paused" ? publish({ ...snapshot, status: "running" }) : reset(true)}>{snapshot.status === "paused" ? "继续游戏" : snapshot.status === "ready" ? "开始游戏" : "重新开始"}</button></div>}</div><div className="touch-controls" aria-label="触屏方向控制"><button aria-label="向上移动" onPointerDown={press("up")} onPointerUp={release("up")} onPointerCancel={release("up")}>↑</button><div><button aria-label="向左移动" onPointerDown={press("left")} onPointerUp={release("left")} onPointerCancel={release("left")}>←</button><button aria-label="向下移动" onPointerDown={press("down")} onPointerUp={release("down")} onPointerCancel={release("down")}>↓</button><button aria-label="向右移动" onPointerDown={press("right")} onPointerUp={release("right")} onPointerCancel={release("right")}>→</button></div></div></>;
}
