"use client";

import { demoGameStyles } from "@/data/demo-game";
import type { GameStyleId } from "@/types/game";
import type { DeepSeekServiceStatus } from "@/lib/studio/generation-status";

export type IdeaSource = "custom" | "star-dodge";
type PromptPanelProps = { prompt: string; source: IdeaSource; selectedStyle: GameStyleId; onPromptChange: (prompt: string) => void; onTemplateSelect: () => void; onStyleChange: (style: GameStyleId) => void; onGenerate: () => void; notice: string; error: string; isGenerating: boolean; mode: "ai" | "demo"; serviceStatus: DeepSeekServiceStatus };

export function PromptPanel({ prompt, source, selectedStyle, onPromptChange, onTemplateSelect, onStyleChange, onGenerate, notice, error, isGenerating, mode, serviceStatus }: PromptPanelProps) {
  const custom = source === "custom";
  const fallbackMessage = serviceStatus === "missing" ? "尚未配置 DeepSeek AI 服务，仍可使用风格预设继续试玩 Demo 游戏。" : serviceStatus === "connected" ? "DeepSeek 已连接；如果本次生成失败，当前 Demo 会被保留，可直接重新尝试。" : "可先试玩 Demo，填写创意后使用 DeepSeek AI 生成游戏。";
  return <section className="prompt-panel" aria-labelledby="prompt-title"><div className="panel-title"><p className="eyebrow">创建新游戏</p><h1 id="prompt-title">告诉我你的创意</h1><p>{mode === "ai" ? "AI 模式会安全生成当前躲避引擎可运行的游戏规则。" : "Demo 回退模式下，你仍可试玩预设的星际闪避。"}</p></div><div className="engine-source"><span>当前引擎：躲避类</span><b className={custom ? "custom-source" : "template-source"}>{custom ? "自定义 AI 创意" : "起始模板：星际闪避"}</b></div><label className="field-label" htmlFor="game-prompt">游戏需求</label><textarea id="game-prompt" value={prompt} onChange={(event) => onPromptChange(event.target.value)} rows={6} aria-describedby="prompt-help" disabled={isGenerating} /><p id="prompt-help" className="field-help">可自由描述创意；当前引擎会安全适配为躲避类玩法。</p><fieldset><legend className="field-label">起始模板</legend><p className="field-help template-heading-help">仅用于快速填充创意，不会限制 AI 生成结果。</p><div className="tag-row"><button type="button" className={`tag ${source === "star-dodge" ? "selected-tag" : ""}`} aria-pressed={source === "star-dodge"} onClick={onTemplateSelect}>星际闪避</button><button type="button" className="tag tag-disabled" disabled aria-disabled="true">接金币 <span>即将支持</span></button><button type="button" className="tag tag-disabled" disabled aria-disabled="true">迷你迷宫 <span>即将支持</span></button></div></fieldset><fieldset disabled={isGenerating}><legend className="field-label">游戏风格</legend><div className="style-options">{Object.values(demoGameStyles).map((style) => <button type="button" key={style.id} className={`style-option ${selectedStyle === style.id ? "selected" : ""}`} aria-pressed={selectedStyle === style.id} onClick={() => onStyleChange(style.id)}><span className={`style-swatch ${style.id}`} />{style.label}</button>)}</div></fieldset><button className="button button-primary generate-button" type="button" onClick={onGenerate} disabled={isGenerating}>{isGenerating ? "AI 正在构建游戏规则…" : "✦ 使用 AI 生成小游戏"}</button>{notice && <p className="demo-notice" role="status">✓ {notice}</p>}{error && <p className="generation-error" role="alert">{error}</p>}<div className="demo-callout"><span aria-hidden="true">ⓘ</span><p><b>{mode === "ai" ? "AI 模式" : "Demo 回退模式"}</b><br />{mode === "ai" ? "AI 只会返回安全的躲避类游戏配置，不会运行生成的代码。" : fallbackMessage}</p></div></section>;
}
